#!/sbin/sh

cat /sys/devices/platform/ab8500-i2c.0/ab8500-usb.0/boot_time_device > /sys/devices/platform/ab8500-i2c.0/ab8500-usb.0/boot_time_device

echo 0 >/sys/class/android_usb/android0/enable
echo 0FCE >/sys/class/android_usb/android0/idVendor
echo 617E >/sys/class/android_usb/android0/idProduct
echo "mass_storage,adb" >/sys/class/android_usb/android0/functions
echo 1 >/sys/class/android_usb/android0/enable

# include device specific vars
source /sbin/bootrec-device

# trigger device specific LED
if [ -e /sbin/bootrec-led ]
then
	./sbin/bootrec-led
fi

# keycheck
cat ${BOOTREC_EVENT} > /dev/keycheck&
sleep 3

# kill the keycheck process
pkill -f "cat ${BOOTREC_EVENT}"

if [ -s /dev/keycheck ] || busybox grep -q warmboot=0x5502 /proc/cmdline
then

  rm /init
  rm -r *.rc
  rm -r /etc
  rm -r /tmp
  mkdir /etc
  mkdir /tmp

  cd / && gunzip < /sbin/recovery_ramdisk.gz | cpio -i -d
  exec /init

fi

# continue booting
# allways remount system ro
  mount -o remount,ro /system
