#!/system/bin/sh

# Clean the DHCP leases before starting...
rm -f /data/misc/dhcp/dhcpcd-wlan0.lease
rm -f /data/misc/dhcp/dhcpcd-wlan0.pid

# Copy hostap.conf to data wifi if it doesnt exists...
if [ ! -f /data/misc/wifi/hostapd.conf ]; then
    cp /system/etc/wifi/hostapd.conf /data/misc/wifi/hostapd.conf
    chown system.wifi /data/misc/wifi/hostapd.conf
    chmod 660 /data/misc/wifi/hostapd.conf
fi

# Copy dhcpcd.conf to data dhcpcd if it doesnt exists...
if [ ! -f /data/misc/dhcpcd/dhcpcd.conf ]; then
    cp /system/etc/dhcpcd/dhcpcd.conf /data/misc/dhcpcd/dhcpcd.conf
    chown dhcp.dhcp 
    chmod 660 /data/misc/dhcpcd/dhcpcd.conf
fi

# Copy wpa_supplicant.conf to data wifi if it doesnt exists...
if [ ! -f /data/misc/wifi/wpa_supplicant.conf ]; then
    cp /system/etc/wifi/wpa_supplicant.conf /data/misc/wifi/wpa_supplicant.conf
fi
if [ -f /data/misc/wifi/wpa_supplicant.conf ]; then
     chown wifi.wifi /data/misc/wifi/wpa_supplicant.conf
     chmod 660 /data/misc/wifi/wpa_supplicant.conf
fi

# Create ipconfig.txt if it doesnt exists...  (Needed for WifiConfigStore)
if [ ! -f /data/misc/wifi/ipconfig.txt ]; then
     touch /data/misc/wifi/ipconfig.txt
     chown system.wifi /data/misc/wifi/ipconfig.txt
fi
